create table user
(
    id       int generated by default as identity not null,
    username varchar(255) unique                  not null,
    password varchar(255)                         not null,
    primary key (id)
)