create table timer
(
    id      int generated by default as identity not null,
    user_id int unique                           not null,
    seconds int                                  not null default 120,
    primary key (id),
    foreign key (user_id) references USER (id)
        on delete cascade
);
